library(reshape)
library(ggplot2)
tmp.dat=read.table("test.ori.freqs.tmp")
tmp.df=data.frame(tmp.dat)
names(tmp.df)<-c("Position", "Phred","A->A","A->C","A->G","A->T","A->N","C->A","C->C","C->G","C->T","C->N","G->A","G->C","G->G","G->T","G->N","T->A","T->C","T->G","T->T","T->N")
tmp.melted<-melt(tmp.df,id.var=c("Position","Phred"))
names(tmp.melted)<-c("Position","Phred","Substitution","Frequency")
tmp.melted$Reference<-substr(tmp.melted$Substitution,1,1)
qplot(Position,Phred,group=Position, data=tmp.melted,weight=Frequency,geom="boxplot",facets=Reference~.)